### ISSUE TITLE
Style error with black square used to blur information

### ISSUE THREAD

**Issue by ByMykel** [RobinMalfait/simple-invoice#17]
I have notice that the black square used to blur information is over some elements like the dashboard header. 

I don't know if this is a bug or a desired behavior.

![image](https://github.com/RobinMalfait/simple-invoice/assets/38622893/8fb6ed92-7317-47a9-b400-32035215f89b)

**Comment by RobinMalfait** [comment]
Hey! Nice catch, this should be fixed 💪
